<ol>
    <li>Undefined</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>System</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>Cmdline</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>Power</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>MAnet</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>USB</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
    <li>Chat</li>
    <ol>
        <li>Undefined</li>
        <li>Spam</li>
        <li>Warnings</li>
        <li>Errors</li>
        <li>Alerts</li>
    </ol>
</ol>

