<ol start="10">
    <li>VirtualKeys</li>
    <ol>
        <li>MA1</li>
        <li>MA2</li>
        <li>PREV</li>
        <li>PREV</li>
        <li>PREV</li>
        <li>PREV</li>
        <li>NEXT</li>
        <li>NEXT</li>
        <li>NEXT</li>
        <li>NEXT</li>
        <li>RESET</li>
        <li>RESET</li>
        <li>RESET</li>
        <li>UP</li>
        <li>UP</li>
        <li>SELFIX</li>
        <li>SELFIX</li>
        <li>DOWN</li>
        <li>MENU</li>
        <li>HIGH</li>
        <li>HIGH</li>
        <li>HIGH</li>
        <li>SOLO</li>
        <li>FREEZE</li>
        <li>PREVIEW</li>
        <li>BLIND</li>
        <li>PAGE_UP</li>
        <li>PAGE_DOWN</li>
        <li>LIST</li>
        <li>LIST</li>
        <li>LIST</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X1</li>
        <li>X2</li>
        <li>X2</li>
        <li>X2</li>
        <li>X2</li>
        <li>X3</li>
        <li>X3</li>
        <li>X3</li>
        <li>X3</li>
        <li>X3</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X4</li>
        <li>X5</li>
        <li>X5</li>
        <li>X5</li>
        <li>X5</li>
        <li>X5</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X6</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X7</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X8</li>
        <li>X9</li>
        <li>X9</li>
        <li>X9</li>
        <li>X9</li>
        <li>X10</li>
        <li>X10</li>
        <li>X10</li>
        <li>X10</li>
        <li>X11</li>
        <li>X11</li>
        <li>X11</li>
        <li>X11</li>
        <li>X12</li>
        <li>X12</li>
        <li>X12</li>
        <li>X12</li>
        <li>X13</li>
        <li>X13</li>
        <li>X13</li>
        <li>X13</li>
        <li>X13</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X14</li>
        <li>X15</li>
        <li>X15</li>
        <li>X15</li>
        <li>X15</li>
        <li>X15</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>X16</li>
        <li>EXEC</li>
        <li>FADER</li>
        <li>DEF_GO</li>
        <li>DEF_GO</li>
        <li>DEF_GO</li>
        <li>DEF_PAUSE</li>
        <li>DEF_GOBACK</li>
        <li>PAUSE</li>
        <li>PAUSE</li>
        <li>PAUSE</li>
        <li>PAUSE</li>
        <li>GOBACK</li>
        <li>GOBACK</li>
        <li>GOBACK</li>
        <li>GO</li>
        <li>GO</li>
        <li>GO</li>
        <li>GO</li>
        <li>GO</li>
        <li>GO</li>
        <li>LEARN</li>
        <li>LEARN</li>
        <li>LEARN</li>
        <li>GOBACKFAST</li>
        <li>GOBACKFAST</li>
        <li>GOBACKFAST</li>
        <li>GOFAST</li>
        <li>GOFAST</li>
        <li>GOFAST</li>
        <li>ON</li>
        <li>ON</li>
        <li>OFF</li>
        <li>MOVE</li>
        <li>MOVE</li>
        <li>COPY</li>
        <li>COPY</li>
        <li>COPY</li>
        <li>COPY</li>
        <li>COPY</li>
        <li>DELETE</li>
        <li>DELETE</li>
        <li>DELETE</li>
        <li>ALIGN</li>
        <li>ALIGN</li>
        <li>ALIGN</li>
        <li>STOMP</li>
        <li>STOMP</li>
        <li>HELP</li>
        <li>SELECT</li>
        <li>SELECT</li>
        <li>GOTO</li>
        <li>GOTO</li>
        <li>GOTO</li>
        <li>GOTO</li>
        <li>GOTO</li>
        <li>GOTO</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>FIXTURE</li>
        <li>CHANNEL</li>
        <li>GROUP</li>
        <li>GROUP</li>
        <li>GROUP</li>
        <li>SEQUENCE</li>
        <li>CUE</li>
        <li>CUE</li>
        <li>CUE</li>
        <li>CUE</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>PRESET</li>
        <li>EDIT</li>
        <li>EDIT</li>
        <li>ASSIGN</li>
        <li>ASSIGN</li>
        <li>ASSIGN</li>
        <li>TIME</li>
        <li>UPDATE</li>
        <li>UPDATE</li>
        <li>UPDATE</li>
        <li>UPDATE</li>
        <li>UPDATE</li>
        <li>STORE</li>
        <li>STORE</li>
        <li>STORE</li>
        <li>NUM0</li>
        <li>NUM1</li>
        <li>NUM1</li>
        <li>NUM2</li>
        <li>NUM2</li>
        <li>NUM2</li>
        <li>NUM2</li>
        <li>NUM3</li>
        <li>NUM3</li>
        <li>NUM4</li>
        <li>NUM4</li>
        <li>NUM4</li>
        <li>NUM4</li>
        <li>NUM5</li>
        <li>NUM5</li>
        <li>NUM5</li>
        <li>NUM5</li>
        <li>NUM6</li>
        <li>NUM6</li>
        <li>NUM6</li>
        <li>NUM6</li>
        <li>NUM7</li>
        <li>NUM7</li>
        <li>NUM8</li>
        <li>NUM8</li>
        <li>NUM8</li>
        <li>NUM8</li>
        <li>NUM9</li>
        <li>NUM9</li>
        <li>PLUS</li>
        <li>PLUS</li>
        <li>THRU</li>
        <li>MINUS</li>
        <li>MINUS</li>
        <li>DOT</li>
        <li>DOT</li>
        <li>DOT</li>
        <li>DOT</li>
        <li>IF</li>
        <li>AT</li>
        <li>AT</li>
        <li>AT</li>
        <li>AT</li>
        <li>AT</li>
        <li>AT</li>
        <li>AT</li>
        <li>SLASH</li>
        <li>SLASH</li>
        <li>SLASH</li>
        <li>PLEASE</li>
        <li>PLEASE</li>
        <li>PLEASE</li>
        <li>FULL</li>
        <li>UNDO</li>
        <li>CLEAR</li>
        <li>ESC</li>
        <li>ENCODER_INSIDE1</li>
        <li>ENCODER_OUTSIDE1</li>
        <li>ENCODER_INSIDE2</li>
        <li>ENCODER_OUTSIDE2</li>
        <li>ENCODER_INSIDE3</li>
        <li>ENCODER_OUTSIDE3</li>
        <li>ENCODER_INSIDE4</li>
        <li>ENCODER_OUTSIDE4</li>
        <li>ENCODER_INSIDE5</li>
        <li>ENCODER_OUTSIDE5</li>
        <li>USER1</li>
        <li>USER2</li>
        <li>XKEYS</li>
    </ol>
</ol>