<ol start="15">
    <li>ColorTheme</li>
    <ol>
        <li>ColorDefCollect</li>
        <ol>
            <li>Global</li>
            <ol>
                <ol>
                    <li>Text</li>
                    <li>TextDefault</li>
                    <li>TextDark</li>
                    <li>Background</li>
                    <li>BackgroundDark</li>
                    <li>Header</li>
                    <li>AltHeader</li>
                    <li>DefaultCellBackground</li>
                    <li>DefaultCellAltBackground</li>
                    <li>Selected</li>
                    <li>SelectedInverted</li>
                    <li>SelectedEdge</li>
                    <li>InvalidGridPosition</li>
                    <li>MainMultiPatchSelected</li>
                    <li>PartlySelected</li>
                    <li>SelectedPreset</li>
                    <li>PartlySelectedPreset</li>
                    <li>BackgroundSelected</li>
                    <li>BackgroundInvalidGridPosition</li>
                    <li>BackgroundMainMultiPatchSelected</li>
                    <li>BackgroundSelectedInverted</li>
                    <li>Connected</li>
                    <li>Lasso</li>
                    <li>FocusFrame</li>
                    <li>WindowFocus</li>
                    <li>Hover</li>
                    <li>SelectedFrameBackground</li>
                    <li>SelectedRowBorder</li>
                    <li>Pressed</li>
                    <li>ButtonBackground</li>
                    <li>ActiveIcon</li>
                    <li>Inactive</li>
                    <li>Bright</li>
                    <li>TitleGray</li>
                    <li>LabelText</li>
                    <li>IndicatorBar</li>
                    <li>ButtonBackgroundDarker</li>
                    <li>PropertyBackground</li>
                    <li>PropertyBackgroundActive</li>
                    <li>Fixed</li>
                    <li>Icon</li>
                    <li>ButtonIndicatorIcon</li>
                    <li>IconHover</li>
                    <li>RedIndicator</li>
                    <li>DarkRedIndicator</li>
                    <li>GreenIndicator</li>
                    <li>DarkGreenIndicator</li>
                    <li>YellowIndicator</li>
                    <li>OrangeIndicator</li>
                    <li>CyanIndicator</li>
                    <li>UpdateIndicator</li>
                    <li>UpdateAddIndicator</li>
                    <li>UpdateIntegrated</li>
                    <li>UpdateAddIntegrated</li>
                    <li>Warning</li>
                    <li>Error</li>
                    <li>Alert</li>
                    <li>Success</li>
                    <li>RedBackground</li>
                    <li>OverlayBackground</li>
                    <li>GreenBackground</li>
                    <li>Shadow</li>
                    <li>ShadowDark</li>
                    <li>DeskLock</li>
                    <li>Disabled</li>
                    <li>Referenced</li>
                    <li>AfterGlow</li>
                    <li>GlobalPreset</li>
                    <li>SelectivePreset</li>
                    <li>UniversalPreset</li>
                    <li>ForSome</li>
                    <li>ForAll</li>
                    <li>ForNone</li>
                    <li>Lightened</li>
                    <li>Darkened</li>
                    <li>Transparent</li>
                    <li>Transparent25</li>
                    <li>Transparent50</li>
                    <li>Transparent75</li>
                    <li>Parked</li>
                    <li>RemoteInputLock</li>
                    <li>TextViewSelectedRow</li>
                    <li>TextViewBackground</li>
                    <li>TextViewFixedBackground</li>
                    <li>Collected</li>
                    <li>UserChanged</li>
                </ol>
            </ol>
            <li>SheetColor</li>
            <ol>
                1-48 color definition
            </ol>
            <li>Playback</li>
            <ol>
                1-21 color definition
            </ol>
            <li>PoolDefault</li>
            <ol>
                1-31 color definition
            </ol>
        </ol>
        <li>ColorGroups</li>
        <ol>
            1-90 color definition
        </ol>
    </ol>
</ol>
